### ISSUE TITLE
type 'Null' is not a subtype of type 'Function'

### ISSUE THREAD

**Issue by YousufSohail** [peiffer-innovations/json_dynamic_widget#104]
I am trying to render a sample screen using [buttons.json](https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/buttons.json) file provided in the example project here. But I am getting this exception. Other examples working fine. What could be the issue?

```
======== Exception caught by widgets library =======================================================
The following HandledJsonWidgetException was thrown building Builder:
*** HandledJsonWidgetException ***
{
  "type": "elevated_button",
  "args": {
    "onLongPress": "${simplePrintMessage()}",
    "style": {
      "foregroundColor": {
        "pressed": "FF2196F3",
        "focused": "FF2196F3",
        "empty": "FFF44336"
      }
    }
  },
  "child": {
    "type": "text",
    "args": {
      "text": "ElevatedButton"
    }
  }
}
type 'Null' is not a subtype of type 'Function'
#0      ArgsExpressionEvaluator.evalCallExpression (package:json_dynamic_widget/src/components/processors/expression_arg_processor.dart:118:31)
#1      ExpressionEvaluator.eval (package:template_expressions/src/expressions/evaluator.dart:111:16)
#2      ArgsExpressionEvaluator.evaluate (package:json_dynamic_widget/src/components/processors/expression_arg_processor.dart:64:52)
#3      ExpressionArgProcessor.process (package:json_dynamic_widget/src/components/processors/expression_arg_processor.dart:37:23)
#4      JsonWidgetRegistry.processArgs (package:json_dynamic_widget/src/components/json_widget_registry.dart:251:10)
#5      MapArgProcessor.process.<anonymous closure> (package:json_dynamic_widget/src/components/processors/map_arg_processor.dart:51:20)
#6      Iterable.forEach (dart:core/iterable.dart:325:35)
#7      MapArgProcessor.process (package:json_dynamic_widget/src/components/processors/map_arg_processor.dart:48:17)

```

**Comment by crisperit** [comment]
If you are trying to use that example in your project then you have to remember to add custom function - `simplePrintMessage`  to your registry

```
registry.registerFunctions({
        'simplePrintMessage': ({args, required registry}) => () {
          var message = 'This is a simple print message';
          if (args?.isEmpty == false) {
            for (var arg in args!) {
              message += ' $arg';
            }
          }
          // ignore: avoid_print
          print(message);
        },
});
```

**Comment by YousufSohail** [comment]
Do we have that in our example? @crisperit

**Comment by YousufSohail** [comment]
Got that, thanks!
