### ISSUE TITLE
Is widget IconButton supported?

### ISSUE THREAD

**Issue by bhtri** [peiffer-innovations/json_dynamic_widget#24]
First of all I want to thank the owner for such a wonderful library.
I tried creating a simple json structure like this, and using `FutureBuilder` to build a simple page.
<details>
  <summary>json</summary>

```
{
    "type": "scaffold",
    "args": {
      "appBar": {
        "type": "app_bar",
        "args": {
          "title": {
            "type": "text",
            "args": {
              "text": "List of English words"
            }
          },
          "actions": [
            {
              "type": "icon_button",
              "args": {
                "icon": {
                  "codePoint": 59418,
                  "fontFamily": "MaterialIcons",
                  "matchTextDirection": true
                },
                "onPressed": "##click()##"
              }
            }
          ]
        }
      },
      "body": {
        "type": "center",
        "child": {
          "type": "circular_progress_indicator",
          "args": {
            "valueColor": "#f00"
          }
        }
      }
    }
  }
```

</details>
but received an error  `The offending widget is: FutureBuilder<Response>`
<details>
  <summary>error log</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building FutureBuilder<Response>(dirty, state:
flutter: _FutureBuilderState<Response>#efc7f):
flutter: A build function returned null.
flutter: The offending widget is:
flutter:   FutureBuilder<Response>
flutter: Build functions must never return null.
flutter: To return an empty space that causes the building widget to fill available room, return
flutter: "Container()". To return an empty space that takes as little room as possible, return
flutter: "Container(width: 0.0, height: 0.0)".
flutter:
flutter: The relevant error-causing widget was:
flutter:   FutureBuilder<Response>
flutter:   file:///$HOME/jsonDesignExample/lib/dynamic_widget.dart:20:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      debugWidgetBuilderValue.<anonymous closure> (package:flutter/src/widgets/debug.dart:302:7)
flutter: #1      debugWidgetBuilderValue (package:flutter/src/widgets/debug.dart:323:4)
flutter: #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4632:7)
flutter: #3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
flutter: #6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
flutter: #7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
flutter: #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #14     _invoke (dart:ui/hooks.dart:251:10)
flutter: #15     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>
<details>
  <summary>dynamic_widget.dart</summary>

```
class DynamicWidget extends StatefulWidget {
  final url = 'https://~/jsonDesignExample/html/my.json';

  @override
  State<StatefulWidget> createState() {
    // implement createState
    return _DynamicWidgetState();
  }
}

class _DynamicWidgetState extends State<DynamicWidget> {
  @override
  Widget build(BuildContext context) {
    // implement build
    return FutureBuilder(
      builder: (context, AsyncSnapshot<http.Response> snapshot) {
        if (snapshot.hasData) {
          JsonWidgetRegistry.instance.clearValues();
          var widgetJson = jsonDecode(snapshot.data.body);
          var widget = JsonWidgetData.fromDynamic(widgetJson);
          return widget.build(
            context: context,
          );
        } else {
          return Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }
      },
      future: _getWidget(),
    );
  }

  Future<http.Response> _getWidget() async {
    return await http.get(widget.url);
  }
}
```
</details>
Am I doing anything wrong with the library or Flutter?

Thank you so much for your help ^_^

**Comment by jpeiffer** [comment]
It was not a supported widget, but as of today / `1.4.1` it is.

I took your issue and turned it into one of the `example` items.  I'm going to go ahead and close this issue.  Please re-open if you don't think it's fully resolved.
